### ISSUE TITLE
Copia de landing ESLAND.

### ISSUE THREAD

**Issue by marsidev** [dannyribes/mystic-bcn#1]
Este repositorio es una vil copia de [midudev/esland-web](https://github.com/midudev/esland-web).

![image](https://github.com/dannyribes/mystic-bcn/assets/56328053/515b7117-46e3-4ec0-8b8b-08a011c2ee6a)
![image](https://github.com/dannyribes/mystic-bcn/assets/56328053/eb03c53b-6a90-46d0-8fda-30098ea55f3c)

No tuviste la decencia de hacer un fork (para conservar el historial de commits) ni de hacer mención al creador: @midudev

En este commit se puede ver cómo reemplazaste el contenido de la página original: https://github.com/dannyribes/mystic-bcn/commit/180c243adc104abac792b266e1780353df05c021#diff-3d2b8ccdb3850b6099424cae3ce1892730315e9c6819a3761c0bc0c336937d23

Por favor, añade los créditos correspondientes.

**Comment by dannyribes** [comment]
Hola Luis. No tengo ningún problema en mencionar la comunidad de desarrolladores que colaboráis con midudev y a midudev mismo, lo que pasa es que pensé que os iba a molestar que os mencionase en esa página web sin vuestro permiso. Es por esto que escribí un correo a @midudev para pedirle autorización y soporte para acabarla. Ahora mismo paso a citar a @midudev y toda la comunidad como los autores legítimos

**Comment by dannyribes** [comment]
Hola Luis. Ya he actualizado la web acreditando a los autores. Echa un vistazo a mystic-bcn.com
Un saludo, 

Daniel
