### ISSUE TITLE
Problema con el autor/es de la web.

### ISSUE THREAD

**Issue by edglz** [dannyribes/mystic-bcn#5]
### Colega desarrollador.

Al menos da créditos o al menos haz el fork desde el proyecto original. Me parece de mal gusto que pongas en la misma web.

![image](https://github.com/dannyribes/mystic-bcn/assets/122640934/3d05cf09-4b78-4f66-adea-768b697bde2b)

Se espera un nuevo deploy con los creditos a la comunidad de @midudev y el mismo.

**Comment by dannyribes** [comment]
Hola. Pues la verdad es que tienes razón. Voy a hacer el nuevo deploy en breve. Es que me da un error el código y no puedo volver a desplegarlo hasta que no lo solucione. Un saludo

**Comment by edglz** [comment]
## Gracias, por el aporte, muchas gracias colega :)!
![image](https://github.com/dannyribes/mystic-bcn/assets/122640934/b3867cac-3b97-47d2-ae8c-4befdb00a6d9)
